/* Component tests generated by react-snapshot-test-generator on 2018-03-26T05:01:49.472Z */

import React from 'React'
import renderer from 'react-test-renderer'

function snapshotTest(element) {
  const tree = renderer.create(element).toJSON()
  expect(tree).toMatchSnapshot()
}



import Header from '../components/Header'
import Movie from '../components/Movie'
import MovieForm from '../components/MovieForm'
import MovieTable from '../components/MovieTable'


describe(`<Header />`, () => {
  it('renders correctly', () => {
    snapshotTest(<Header />)
  })
})

describe(`<Movie />`, () => {
  it('renders correctly', () => {
    snapshotTest(<Movie />)
  })
})

describe(`<MovieForm />`, () => {
  it('renders correctly', () => {
    snapshotTest(<MovieForm />)
  })
})

describe(`<MovieTable />`, () => {
  it('renders correctly', () => {
    snapshotTest(<MovieTable />)
  })
})
